services:
  mysql:
    image: mysql:8.0
    container_name: mysql-prod
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: player_management_db_prod
    ports:
      - "3306:3306"
    volumes:
      - mysql_data_prod:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: on-failure
  backend:
    build:
      context: ./PlayerService
    container_name: player-service-prod
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-prod:3306/player_management_db_prod?useSSL=true&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      LOGGING_FILE_NAME: /app/logs/app.log
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://0.0.0.0:8080/actuator/health"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: on-failure
  frontend:
    container_name: frontend-prod
    build:
      context: ./PlayersDashboard
      target: prod
    environment:
      VITE_BACKEND_HOST: localhost
      VITE_BACKEND_PORT: 8080
    ports:
      - "80:80" #Dedicated port for production under security measures !!!
    depends_on:
      - backend
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://0.0.0.0/index.html"]
      interval: 30s
      timeout: 10s
      retries: 20
volumes:
  mysql_data_prod: 