name: CI for Player Management System

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log Step 1
        run: |
          echo "Step 1: Checkout repository" | tee -a ci_cd_log.txt

      # 2. JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"

      # 3. dos2unix
      - name: Convert gradlew to Unix format
        run: |
          sudo apt-get update && sudo apt-get install -y dos2unix
          dos2unix ./PlayerService/gradlew
          echo "Converted gradlew to Unix format" | tee -a ci_cd_log.txt

      # 4. chmod gradlew
      - name: Set execution permission for gradlew
        run: |
          chmod +x ./PlayerService/gradlew
          echo "Execution permission set for gradlew" | tee -a ci_cd_log.txt

      # 5. Tests
      - name: Run backend tests
        run: |
          echo "Running backend tests..." | tee -a ci_cd_log.txt
          cd PlayerService
          ../PlayerService/gradlew test --no-daemon | tee -a ../ci_cd_log.txt
          cd ..

      # 6. Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log Step 2
        run: |
          echo "Step 2: Set up Docker Buildx" | tee -a ci_cd_log.txt

      # 7. Login to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUBUSERNAME }}
          password: ${{ secrets.DOCKERHUBPASSWORD }}

      # 7.5 Create frontend env
      - name: Create .env.prod for frontend
        run: |
          cat <<EOF > PlayersDashboard/.env.prod
          VITE_PORT=${{ secrets.VITEPORT }}
          VITE_BACKEND_HOST=${{ secrets.VITEBACKENDHOST }}
          VITE_BACKEND_PORT${{secrets.VITEBACKENDPORT}}
          EOF

      # 8. Build & Push (now including mysql)
      - name: Build Docker Compose Images and Push to Docker Hub
        run: |
          echo "Step 3: Build images" | tee -a ci_cd_log.txt
          sudo apt-get update | tee -a ci_cd_log.txt
          sudo apt-get install -y docker-compose-plugin | tee -a ci_cd_log.txt
          docker compose version | tee -a ci_cd_log.txt

          docker compose -f docker-compose.prod.yml build | tee -a ci_cd_log.txt

          echo "=== Docker images after build ===" | tee -a ci_cd_log.txt
          docker images --format '{{.Repository}}:{{.Tag}}' | tee -a ci_cd_log.txt

          # Retag & push mysql, backend and frontend
          for SERVICE in mysql backend frontend; do
            IMAGE=$(docker images \
              --filter "label=com.docker.compose.service=$SERVICE" \
              --format '{{.Repository}}:{{.Tag}}' | head -n1)

            if [ -z "$IMAGE" ]; then
              echo "No image found for service $SERVICE" | tee -a ci_cd_log.txt
              continue
            fi

            # extract original tag (after the last ':')
            TAG="${IMAGE##*:}"

            TARGET="players-dashboard-system/$SERVICE:$TAG"
            echo "Tagging $IMAGE → $TARGET" | tee -a ci_cd_log.txt
            docker tag "$IMAGE" "$TARGET" | tee -a ci_cd_log.txt

            echo "Pushing $TARGET" | tee -a ci_cd_log.txt
            docker push "$TARGET" | tee -a ci_cd_log.txt
          done

      # 9. Up
      - name: Start Docker Compose with built images
        run: |
          echo "Step 4: Start Docker Compose" | tee -a ci_cd_log.txt
          docker compose -f docker-compose.prod.yml up -d | tee -a ci_cd_log.txt

      # 10. Down
      - name: Tear Down Docker Compose
        run: |
          echo "Tearing down Docker Compose services..." | tee -a ci_cd_log.txt
          docker compose -f docker-compose.prod.yml down | tee -a ci_cd_log.txt

      # 11. Logs
      - name: Output logs for all services
        run: |
          echo "Service logs:" | tee -a ci_cd_log.txt
          docker compose -f docker-compose.prod.yml logs | tee -a ci_cd_log.txt

      # 12. Upload logs
      - name: Upload log file
        uses: actions/upload-artifact@v4
        with:
          name: build-logs
          path: ci_cd_log.txt
