name: Player Management System CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

env:
  REGISTRY: docker.io
  IMAGE_NAME_BACKEND: ${{ secrets.DOCKERHUBUSERNAME }}/PlayerMangementSystem/player-service
  IMAGE_NAME_FRONTEND: ${{ secrets.DOCKERHUBUSERNAME }}/PlayerMangementSystem/players-dashboard
  IMAGE_NAME_DB: ${{ secrets.DOCKERHUBUSERNAME }}/PlayerMangementSystem/mysql

jobs:
  test-backend:
    name: Test Backend Service
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log Step - Checkout
        run: |
          echo "=== CI/CD LOG ===" > ci_cd_log.txt
          echo "$(date): Step 1 - Checkout repository completed" | tee -a ci_cd_log.txt

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Log Step - Java Setup
        run: |
          echo "$(date): Step 2 - Java 17 setup completed" | tee -a ci_cd_log.txt

      - name: Convert gradlew to Unix format
        run: |
          sudo apt-get update && sudo apt-get install -y dos2unix
          dos2unix ./PlayerService/gradlew
          echo "$(date): Step 3 - Converted gradlew to Unix format" | tee -a ci_cd_log.txt

      - name: Set execution permission for gradlew
        run: |
          chmod +x ./PlayerService/gradlew
          echo "$(date): Step 4 - Execution permission set for gradlew" | tee -a ci_cd_log.txt

      - name: Run Backend Tests
        run: |
          echo "$(date): Step 5 - Starting backend tests..." | tee -a ci_cd_log.txt
          cd PlayerService
          pwd | tee -a ../ci_cd_log.txt
          ./gradlew test --no-daemon --info | tee -a ../ci_cd_log.txt
          if [ $? -eq 0 ]; then
            echo "$(date): ✅ Backend tests passed successfully!" | tee -a ../ci_cd_log.txt
          else
            echo "$(date): ❌ Backend tests failed!" | tee -a ../ci_cd_log.txt
            exit 1
          fi
          cd ..

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: backend-test-results
          path: |
            PlayerService/build/test-results/
            PlayerService/build/reports/tests/
            ci_cd_log.txt

  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    needs: test-backend
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log Step - Build Start
        run: |
          echo "$(date): Step 6 - Starting build and deploy process..." | tee -a ci_cd_log.txt

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log Step - Docker Setup
        run: |
          echo "$(date): Step 7 - Docker Buildx setup completed" | tee -a ci_cd_log.txt

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKERHUBUSERNAME }}
          password: ${{ secrets.DOCKERHUBPASSWORD }}

      - name: Log Step - Docker Login
        run: |
          echo "$(date): Step 8 - Docker Hub login completed" | tee -a ci_cd_log.txt

      - name: Install Docker Compose
        run: |
          echo "$(date): Step 9 - Installing Docker Compose..." | tee -a ci_cd_log.txt
          sudo apt-get update
          sudo apt-get install -y python3-pip
          sudo pip3 install docker-compose
          docker-compose --version | tee -a ci_cd_log.txt

      - name: Build images with Docker Compose
        run: |
          echo "$(date): Step 10 - Building images with Docker Compose..." | tee -a ci_cd_log.txt
          docker-compose -f docker-compose.prod.yml build
          echo "$(date): Step 11 - Docker Compose build completed" | tee -a ci_cd_log.txt

      - name: List built images
        run: |
          echo "$(date): Step 12 - Listing built images..." | tee -a ci_cd_log.txt
          docker images | tee -a ci_cd_log.txt

      - name: Tag and push Backend image
        run: |
          echo "$(date): Step 13 - Tagging and pushing backend image..." | tee -a ci_cd_log.txt
          # Get the actual image name from Docker Compose
          BACKEND_IMAGE=$(docker images --format "table {{.Repository}}:{{.Tag}}" | grep "playermangementsystem_backend" | head -1 | awk '{print $1}')
          echo "Backend image found: $BACKEND_IMAGE" | tee -a ci_cd_log.txt
          docker tag $BACKEND_IMAGE ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_BACKEND }}:main
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_BACKEND }}:main
          echo "$(date): Step 14 - Backend image pushed successfully" | tee -a ci_cd_log.txt

      - name: Tag and push Frontend image
        run: |
          echo "$(date): Step 15 - Tagging and pushing frontend image..." | tee -a ci_cd_log.txt
          # Get the actual image name from Docker Compose
          FRONTEND_IMAGE=$(docker images --format "table {{.Repository}}:{{.Tag}}" | grep "playermangementsystem_frontend" | head -1 | awk '{print $1}')
          echo "Frontend image found: $FRONTEND_IMAGE" | tee -a ci_cd_log.txt
          docker tag $FRONTEND_IMAGE ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_FRONTEND }}:main
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_FRONTEND }}:main
          echo "$(date): Step 16 - Frontend image pushed successfully" | tee -a ci_cd_log.txt

      - name: Test Docker Compose
        run: |
          echo "$(date): Step 17 - Testing Docker Compose setup..." | tee -a ci_cd_log.txt
          docker-compose -f docker-compose.prod.yml up -d
          echo "$(date): Step 18 - Docker Compose services started" | tee -a ci_cd_log.txt

          # Wait for services to be healthy
          echo "$(date): Step 19 - Waiting for services to be healthy..." | tee -a ci_cd_log.txt
          timeout 300 bash -c 'until docker-compose -f docker-compose.prod.yml ps | grep -q "healthy"; do sleep 10; done' || true

          # Check service status
          echo "$(date): Step 20 - Checking service status..." | tee -a ci_cd_log.txt
          docker-compose -f docker-compose.prod.yml ps | tee -a ci_cd_log.txt

          # Test backend health endpoint
          echo "$(date): Step 21 - Testing backend health endpoint..." | tee -a ci_cd_log.txt
          sleep 30
          curl -f http://localhost:8080/actuator/health || echo "Backend health check failed" | tee -a ci_cd_log.txt

          # Test frontend
          echo "$(date): Step 22 - Testing frontend..." | tee -a ci_cd_log.txt
          curl -f http://localhost:80/ || echo "Frontend check failed" | tee -a ci_cd_log.txt

      - name: Tear down Docker Compose
        if: always()
        run: |
          echo "$(date): Step 23 - Tearing down Docker Compose services..." | tee -a ci_cd_log.txt
          docker-compose -f docker-compose.prod.yml down -v
          echo "$(date): Step 24 - Docker Compose services stopped" | tee -a ci_cd_log.txt

      - name: Output service logs
        if: always()
        run: |
          echo "$(date): Step 25 - Service logs:" | tee -a ci_cd_log.txt
          docker-compose -f docker-compose.prod.yml logs || echo "No logs available" | tee -a ci_cd_log.txt

      - name: Upload build logs
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: build-and-deploy-logs
          path: ci_cd_log.txt
          retention-days: 30

      - name: Notify on success
        if: success()
        run: |
          echo "$(date): ✅ CI/CD Pipeline completed successfully!" | tee -a ci_cd_log.txt
          echo "🎉 All tests passed, images built and deployed to Docker Hub"

      - name: Notify on failure
        if: failure()
        run: |
          echo "$(date): ❌ CI/CD Pipeline failed!" | tee -a ci_cd_log.txt
          echo "🚨 Pipeline failed - check logs for details"
